name: run-tests

on: 
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-mocha-tests:
    runs-on: ubuntu-latest
    steps:

      # Elasticsearch
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - uses: getong/elasticsearch-action@v1.2
        with:
          elasticsearch version: '7.6.1'
          host port: 9200
          container port: 9200
          host node port: 9300
          node port: 9300
          discovery type: 'single-node'

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      # Decrypt test .env file
      - run: |
          cd test
          openssl enc -aes-256-cbc -d -in .env.enc -out .env -k ${{ secrets.CBC_ENC_PWD }}
          cd ..
          mv test/.env .
          mv test/cache .

      # Install frontend node dependencies, install Java jdk for Elastic
      - run: |
          npm install
          sudo apt update
          sudo apt install openjdk-8-jdk

      # Start Elastic server, post test data
      - run: |
          sudo service elasticsearch start
          sleep 10
          curl -XPUT http://localhost:9200/repo_test_mocha -d @test/index_schema.json
          curl -XPOST http://localhost:9200/repo_test_mocha/_doc/61ed6a68-618b-48eb-b9bd-3e7484e0590a -d @test/test-collection.json
          curl -XPOST http://localhost:9200/repo_test_mocha/_doc/7479257d-3c34-4e87-8358-05460a828ca1 -d @test/test-object1.json
          curl -XPOST http://localhost:9200/repo_test_mocha/_doc/81c733ec-b597-48d1-9488-90f2a67627ed -d @test/test-object2.json
          curl -XPOST http://localhost:9200/repo_test_mocha/_doc/d3dcaa18-d441-4396-9f0a-887e1277b279 -d @test/test-object3.json
          curl -v http://localhost:9200/
          curl -v http://localhost:9200/repo_test_mocha

      # Start app and run mocha tests
      - run: |
          node discovery.js &
          sleep 10
          npm test
